### ISSUE TITLE
感谢大佬,请问下这个有希望做成一键转pdf到markdown的潜力吗?

### ISSUE THREAD

**Issue by seetimee** [XJF2332/GOT-OCR-2-GUI#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KirariSpark** [comment]
模式选render可以出html，以后可能会考虑做一个出pdf的

**Comment by seetimee** [comment]
🤗
