### ISSUE TITLE
出现报错：The checkpoint you are trying to load has model type `GOT`

### ISSUE THREAD

**Issue by xiumu1988** [XJF2332/GOT-OCR-2-GUI#10]
pip install -r requirements-noversion.txt
之后，运行gui会出现缺少frontend和tools的提示，重新pip install这两个组件以后，运行gui会出现下面这个报错：

Traceback (most recent call last):
  File "D:\AI_Tools\GOT-OCR-2-GUI-main\gui.py", line 55, in <module>
    model, tokenizer = load_model()
  File "D:\AI_Tools\GOT-OCR-2-GUI-main\gui.py", line 38, in load_model
    model = AutoModel.from_pretrained('models', trust_remote_code=True, low_cpu_mem_usage=True, device_map='cuda',
  File "C:\Users\XiuMu\.conda\envs\got\lib\site-packages\transformers\models\auto\auto_factory.py", line 526, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "C:\Users\XiuMu\.conda\envs\got\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1025, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `GOT` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

pip list信息如下：
Package             Version
------------------- ------------
accelerate          1.0.1
aiofiles            23.2.1
annotated-types     0.7.0
anyio               4.6.2.post1
asttokens           2.4.1
attrs               24.2.0
Brotli              1.1.0
certifi             2024.8.30
cffi                1.17.1
charset-normalizer  3.4.0
ci-info             0.3.0
click               8.1.7
colorama            0.4.6
configobj           5.0.9
configparser        7.1.0
contourpy           1.3.0
cssselect2          0.7.0
cycler              0.12.1
decorator           5.1.1
etelemetry          0.3.1
exceptiongroup      1.2.2
executing           2.1.0
fastapi             0.115.2
ffmpy               0.4.0
filelock            3.16.1
fitz                0.0.1.dev2
fonttools           4.54.1
frontend            0.0.3
fsspec              2024.9.0
gobject             0.1.0
gradio              5.1.0
gradio_client       1.4.0
h11                 0.14.0
html5lib            1.1
httpcore            1.0.6
httplib2            0.22.0
httpx               0.27.2
huggingface-hub     0.26.0
idna                3.10
importlib_resources 6.4.5
ipython             8.28.0
isodate             0.6.1
itsdangerous        2.2.0
jedi                0.19.1
Jinja2              3.1.4
kiwisolver          1.4.7
looseversion        1.3.0
lxml                5.3.0
markdown-it-py      3.0.0
MarkupSafe          2.1.5
matplotlib          3.9.2
matplotlib-inline   0.1.7
mdurl               0.1.2
mpmath              1.3.0
networkx            3.4.1
nibabel             5.3.1
nipype              1.8.6
numpy               2.1.2
orjson              3.10.7
outcome             1.3.0.post0
packaging           24.1
pandas              2.2.3
parso               0.8.4
pathlib             1.0.1
pillow              10.4.0
pip                 24.2
pipdeptree          2.23.4
prompt_toolkit      3.0.48
prov                2.0.1
psutil              6.1.0
pure_eval           0.2.3
pycparser           2.22
pydantic            2.9.2
pydantic_core       2.23.4
pydot               3.0.2
pydub               0.25.1
pydyf               0.11.0
Pygments            2.18.0
PyMuPDF             1.24.11
PyMuPDFb            1.24.10
pyparsing           3.2.0
pyphen              0.16.0
PySocks             1.7.1
python-dateutil     2.9.0.post0
python-multipart    0.0.12
pytils              0.4.1
pytz                2024.2
pyxnat              1.6.2
PyYAML              6.0.2
rdflib              6.3.2
regex               2024.9.11
requests            2.32.3
rich                13.9.2
ruff                0.7.0
safetensors         0.4.5
scipy               1.14.1
selenium            4.25.0
semantic-version    2.10.0
setuptools          75.1.0
shellingham         1.5.4
simplejson          3.19.3
six                 1.16.0
sniffio             1.3.1
sortedcontainers    2.4.0
stack-data          0.6.3
starlette           0.40.0
sympy               1.13.1
tiktoken            0.8.0
tinycss2            1.3.0
tokenizers          0.20.1
tomlkit             0.12.0
tools               0.1.9
torch               2.5.0+cu124
torchaudio          2.5.0+cu124
torchvision         0.20.0+cu124
tqdm                4.66.5
traitlets           5.14.3
traits              6.3.2
transformers        4.45.2
trio                0.27.0
trio-websocket      0.11.1
typer               0.12.5
typing_extensions   4.12.2
tzdata              2024.2
urllib3             2.2.3
uvicorn             0.32.0
verovio             4.3.1
wcwidth             0.2.13
webencodings        0.5.1
websocket-client    1.8.0
websockets          12.0
wheel               0.44.0
wsproto             1.2.0
zopfli              0.2.3.post1

**Comment by KirariSpark** [comment]
看下模型文件夹

**Comment by xiumu1988** [comment]
![图片](https://github.com/user-attachments/assets/198254d1-5ba6-447a-b28f-7d0c49554bde)

**Comment by xiumu1988** [comment]
Python 3.10.15

**Comment by KirariSpark** [comment]
看起来是环境的问题
py3.10的依赖可以试一下这个
torch==2.0.1
torchvision==0.15.2
transformers==4.37.2
tiktoken==0.6.0
verovio==4.3.1
accelerate==0.28.0

**Comment by KirariSpark** [comment]
另外，你也是因为requirements.txt有问题才用的requirements-noversion.txt吗？

**Comment by xiumu1988** [comment]
嗯，对的

**Comment by xiumu1988** [comment]
用了一下别人的整合包，现在已经可以跑了，应该还是环境的问题。
通过百度网盘分享的文件：GOT-OCR-2-GUI-main-fix.rar
链接：https://pan.baidu.com/s/1jtDir8om3Lh9Co5RJnhKZA?pwd=w3ne 
提取码：w3ne
