### ISSUE TITLE
问个特别菜的问题，下载模型到底放在什么目录

### ISSUE THREAD

**Issue by facegbd** [XJF2332/GOT-OCR-2-GUI#2]
我把下载的“GOT-OCR2_0”文件放在了.\GOT\model下，或者放在.\GOT\model\GOT_weights下，甚至放在主目录下。
运行
总是提示
OSError: models is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

此外这个gui的文件和源文件的位置关系是如何？

**Comment by i-square** [comment]
你看看代码就知道了：[GUI-ZH_CN.py#L8](https://github.com/XJF2332/GOT-OCR-2-GUI/blob/main/GUI-ZH_CN.py#L8)

意思就是把你从huggingface下载的目录直接改名为 `models`，放在跟脚本同级的地方，比如脚本在 `test_dir/GUI-ZH_CN.py`，模型目录就是 `test_dir/models`

**Comment by KirariSpark** [comment]
models文件夹，不是model文件夹（

**Comment by KirariSpark** [comment]
顺便更新了一下readme，现在模型路径应该很清楚了

**Comment by facegbd** [comment]
感谢各位的及时帮助，昨天花了十几个小时编译flash_attn  2.6.3，虽然github有编译好的文件但是是linux系统的，我无法使用(也找到了[Windows版本](https://gitcode.com/gh_mirrors/flas/flash-attention/overview)的，但是我也没法正确安装)。总结一下，安装和运行这些python程序的时候，主要就是**解决依赖包，和正确的目录结构**（再次感谢作者，在我求助之后及时的更新了软件目录结构图）。
之前安装got-ocr和got-ocr-2.0-gui失败其实都是fash_attn没有能正确安装导致的。
今天运行正确了之后，又试着在jupyter中调试，则主要遇到的是目录问题，似乎在这种交互式的运行，有一条侦测当前目录的指令不能正确执行。

由于没有编译的经验，直接按照flash_attn官方主页运行了python setup.py install，这样虽然能正确安装，但是却生成了一个egg格式的包，无法pip安装，需要使用setuptools中的eazy_install 安装，但是我试验了一下没法安装成功。必须承认，Python虽然相对简单灵活，但是也是意味着没有规则，就是一座巨大的屎山，就算引入了虚拟环境也不过是造就虚拟化屎山而已。

正常运行之后，发现不能直接处理扫描版的pdf，只能是图片。

再次感谢作者，能够正常的把图片扫描，但是无法保存输出，只能显示在结果框里。

**Comment by ZhangChao1314** [comment]
同样的问题，我从百度云下载的GOT-OCR2.0文件夹，下面有benchmarks和GOT_weights目录，然后我是把GOT_weights下面的所有文件拷贝到新建的models文件夹下面，但是会有'GOT'模型无法transformer的问题，在执行conda的安装包路径下models/auto/**.py的时候报错，提示我torch或者transform out date了（目前用的torch2.4.1+cuda12.4）。我应该怎么解决呢。

**Comment by KirariSpark** [comment]
![image](https://github.com/user-attachments/assets/9320648a-29ae-44de-a07f-d64ceff270b6)
![image](https://github.com/user-attachments/assets/9d2ddb56-e5fe-49fd-ac5e-fc100ef51adc)
度盘的文件和huggingface比起来少了东西，从huggingface下载，上不了huggingface的话README有写镜像站

**Comment by KirariSpark** [comment]
models文件夹应该是这样的
![image](https://github.com/user-attachments/assets/1c837f2f-b0b7-4c12-8631-ae15c555fb67)

**Comment by ZhangChao1314** [comment]
> ![image](https://private-user-images.githubusercontent.com/167102464/370991762-9320648a-29ae-44de-a07f-d64ceff270b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjE5MDUsIm5iZiI6MTcyNzM2MTYwNSwicGF0aCI6Ii8xNjcxMDI0NjQvMzcwOTkxNzYyLTkzMjA2NDhhLTI5YWUtNDRkZS1hMDdmLWQ2NGNlZmYyNzBiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQxNDQwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTMwZTNlOTJmY2Y4OThhNjY5ODI4MDkxYzM3MDk5YzVhYmYyODA5MDFmNjRkMzBjMDYwMTM5N2JmMWIyODYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cAFeGsuD1IJ6LucJZLI22IG-C1gi0vpxrWSyV8JHOng) ![image](https://private-user-images.githubusercontent.com/167102464/370991803-9d2ddb56-e5fe-49fd-ac5e-fc100ef51adc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjE5MDUsIm5iZiI6MTcyNzM2MTYwNSwicGF0aCI6Ii8xNjcxMDI0NjQvMzcwOTkxODAzLTlkMmRkYjU2LWU1ZmUtNDlmZC1hYzVlLWZjMTAwZWY1MWFkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQxNDQwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODc2OGFiOTBiNjY4MjYyMDMxODQxOGQwNGMwZDVlZmI2NmY3MDZiMTY4NTViYjkwMTg1NDg0NmU0Y2NiN2Y0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Df1ePSiVK-WfUhoqSkX1wy-cXKS_xVRC6HKMF9B1VAc) 度盘的文件和huggingface比起来少了东西，从huggingface下载，上不了huggingface的话README有写镜像站

确实我重新用镜像网站下载的模型文件ok了。感谢！render模式，有办法做批处理吗？而且可以加一个html转word的功能吗（找的在线转的都转换效果不是很好）？我还是需要word可编辑的一个文档。

**Comment by KirariSpark** [comment]
批处理暂时没有做这个功能，CLI不接受命令行参数，GUI更不用说。至于转word，你用导出的pdf转word看看，这个模型出的html格式有些特殊，我当时整转pdf都花了一些时间，直接转word估计会更麻烦😢

**Comment by KirariSpark** [comment]
> > ![image](https://private-user-images.githubusercontent.com/167102464/370991762-9320648a-29ae-44de-a07f-d64ceff270b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjE5MDUsIm5iZiI6MTcyNzM2MTYwNSwicGF0aCI6Ii8xNjcxMDI0NjQvMzcwOTkxNzYyLTkzMjA2NDhhLTI5YWUtNDRkZS1hMDdmLWQ2NGNlZmYyNzBiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQxNDQwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTMwZTNlOTJmY2Y4OThhNjY5ODI4MDkxYzM3MDk5YzVhYmYyODA5MDFmNjRkMzBjMDYwMTM5N2JmMWIyODYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cAFeGsuD1IJ6LucJZLI22IG-C1gi0vpxrWSyV8JHOng) ![image](https://private-user-images.githubusercontent.com/167102464/370991803-9d2ddb56-e5fe-49fd-ac5e-fc100ef51adc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjE5MDUsIm5iZiI6MTcyNzM2MTYwNSwicGF0aCI6Ii8xNjcxMDI0NjQvMzcwOTkxODAzLTlkMmRkYjU2LWU1ZmUtNDlmZC1hYzVlLWZjMTAwZWY1MWFkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQxNDQwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODc2OGFiOTBiNjY4MjYyMDMxODQxOGQwNGMwZDVlZmI2NmY3MDZiMTY4NTViYjkwMTg1NDg0NmU0Y2NiN2Y0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Df1ePSiVK-WfUhoqSkX1wy-cXKS_xVRC6HKMF9B1VAc) 度盘的文件和huggingface比起来少了东西，从huggingface下载，上不了huggingface的话README有写镜像站
> 
> 确实我重新用镜像网站下载的模型文件ok了。感谢！render模式，有办法做批处理吗？而且可以加一个html转word的功能吗（找的在线转的都转换效果不是很好）？我还是需要word可编辑的一个文档。

批处理已经做出来了，请查看README里关于Renderer.py的描述
