### ISSUE TITLE
请问下linux环境如何部署这个gui

### ISSUE THREAD

**Issue by dragenxp** [XJF2332/GOT-OCR-2-GUI#3]

**Comment by KirariSpark** [comment]
这下知识盲区了，我甚至没用过linux😫

**Comment by badarrrr** [comment]
我说怎么保存为pdf一直失败😂，原来我是linux环境下的。
实践证明可以部署，把requirements里的依赖安装一下就可以（我是在服务器里跑的，cuda已经安装好了），基本的ocr是可以的，跟wkhtmltopdf有关的应该会报错
![屏幕截图 2024-09-23 142509](https://github.com/user-attachments/assets/0e446e49-349b-4668-9570-5a486332c654)

**Comment by badarrrr** [comment]
或者安装wkhtmltopdf的linux版本 但我没试过 可能代码也得改）

**Comment by KirariSpark** [comment]
新脚本已经迁移到了edge web driver，也许你能试一下？readme有说怎么装

**Comment by KirariSpark** [comment]
以及存pdf要用渲染模式才行，其他模式是不能存的

**Comment by badarrrr** [comment]
render也可以跑通
![image](https://github.com/user-attachments/assets/c0b84340-d18e-4ec9-b9d0-834af33cce1c)
![image](https://github.com/user-attachments/assets/5b2c7505-e162-4ef8-a52f-718d1e7a024d)

**Comment by KirariSpark** [comment]
这样，你看看新的脚本，导pdf已经换成了selenium和edge webdriver，重新装一下依赖再看看能不能用，如果不行的话我也没办法了，我完全不懂linux😂

**Comment by badarrrr** [comment]
我试了一下，在linux里面安装linux版本的wkhtmltopdf，然后把代码里wkhtmltopdf的可执行文件(wkhtmltopdf.exe)路径换成安装好后的可执行文件路径就可以用了 (๑•̀ㅂ•́)و✧

**Comment by HackerTao** [comment]
如果使用linux，可以执行以下代码，完成部署，未实验生成pdf的功能。
```bash
conda create -n got python=3.10 -y
conda activate got
cd /opt
git clone https://github.com/XJF2332/GOT-OCR-2-GUI.git
cd GOT-OCR-2-GUI
pip install -r requirements-noversion.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
mkdir models
wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/model.safetensors
wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/model.safetensors
wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/config.json
wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/modeling_GOT.py
wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/render_tools.py
wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/got_vision_b.py
wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/generation_config.json
wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/qwen.tiktoken
wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/special_tokens_map.json
wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/tokenization_qwen.py
wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/tokenizer_config.json
cd ..
python GUI.py
```
完成无报错后，可以浏览器访问
http://127.0.0.1:7860/

**Comment by sunshinejoesun** [comment]
> 如果使用linux，可以执行以下代码，完成部署，未实验生成pdf的功能。
> 
> ```shell
> conda create -n got python=3.10 -y
> conda activate got
> cd /opt
> git clone https://github.com/XJF2332/GOT-OCR-2-GUI.git
> cd GOT-OCR-2-GUI
> pip install -r requirements-noversion.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
> mkdir models
> wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/model.safetensors
> wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/model.safetensors
> wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/config.json
> wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/modeling_GOT.py
> wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/render_tools.py
> wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/got_vision_b.py
> wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/generation_config.json
> wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/qwen.tiktoken
> wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/special_tokens_map.json
> wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/tokenization_qwen.py
> wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/tokenizer_config.json
> cd ..
> python GUI.py
> ```
> 
> 完成无报错后，可以浏览器访问 http://127.0.0.1:7860/

我在执行python GUI.py时 提示RuntimeError: Directory 'static/' does not exist 这个问题要如何解决呢

**Comment by KirariSpark** [comment]
看一下完整报错信息

**Comment by sunshinejoesun** [comment]
> 看一下完整报错信息
信息如下：
(got) root@autodl-container-433d4a8b09-b280a7e8:~/autodl-tmp/GOT-OCR2.0/opt/GOT-OCR-2-GUI# python GUI.py 
Loading language config...
Loading config......
正在导入库......
Traceback (most recent call last):
  File "/root/autodl-tmp/GOT-OCR2.0/opt/GOT-OCR-2-GUI/GUI.py", line 25, in <module>
    import scripts.PDF2ImagePlusRenderer as PDFHandler
  File "/root/autodl-tmp/GOT-OCR2.0/opt/GOT-OCR-2-GUI/scripts/PDF2ImagePlusRenderer.py", line 1, in <module>
    import fitz
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/fitz/__init__.py", line 1, in <module>
    from frontend import *
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/frontend/__init__.py", line 1, in <module>
    from .events import *
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/frontend/events/__init__.py", line 1, in <module>
    from .clipboard import *
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/frontend/events/clipboard.py", line 2, in <module>
    from ..dom import Event
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/frontend/dom.py", line 439, in <module>
    from . import dispatcher
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/frontend/dispatcher.py", line 15, in <module>
    from . import config, server
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/frontend/server.py", line 24, in <module>
    app.mount(config.STATIC_ROUTE, StaticFiles(directory=config.STATIC_DIRECTORY), name=config.STATIC_NAME)
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/starlette/staticfiles.py", line 56, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'static/' does not exist
(got) root@autodl-container-433d4a8b09-b280a7e8:~/autodl-tmp/GOT-OCR2.0/opt/GOT-OCR-2-GUI#

**Comment by sunshinejoesun** [comment]
> 看一下完整报错信息

(got) root@autodl-container-433d4a8b09-b280a7e8:~/autodl-tmp/GOT-OCR2.0/opt/GOT-OCR-2-GUI# python GUI.py 
Loading language config...
Loading config......
正在导入库......
Traceback (most recent call last):
  File "/root/autodl-tmp/GOT-OCR2.0/opt/GOT-OCR-2-GUI/GUI.py", line 25, in <module>
    import scripts.PDF2ImagePlusRenderer as PDFHandler
  File "/root/autodl-tmp/GOT-OCR2.0/opt/GOT-OCR-2-GUI/scripts/PDF2ImagePlusRenderer.py", line 1, in <module>
    import fitz
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/fitz/__init__.py", line 1, in <module>
    from frontend import *
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/frontend/__init__.py", line 1, in <module>
    from .events import *
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/frontend/events/__init__.py", line 1, in <module>
    from .clipboard import *
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/frontend/events/clipboard.py", line 2, in <module>
    from ..dom import Event
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/frontend/dom.py", line 439, in <module>
    from . import dispatcher
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/frontend/dispatcher.py", line 15, in <module>
    from . import config, server
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/frontend/server.py", line 24, in <module>
    app.mount(config.STATIC_ROUTE, StaticFiles(directory=config.STATIC_DIRECTORY), name=config.STATIC_NAME)
  File "/root/miniconda3/envs/got/lib/python3.10/site-packages/starlette/staticfiles.py", line 56, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'static/' does not exist
(got) root@autodl-container-433d4a8b09-b280a7e8:~/autodl-tmp/GOT-OCR2.0/opt/GOT-OCR-2-GUI#

**Comment by sunshinejoesun** [comment]
> 看一下完整报错信息

![微信截图_20241015214802](https://github.com/user-attachments/assets/3a965bd6-379b-467d-a0ae-e9332efaeb40)

**Comment by KirariSpark** [comment]
import库失败了，应该是没安装好，我是能正常import的
![image](https://github.com/user-attachments/assets/2dce4008-6a0c-4206-9867-39b55976d04d)

**Comment by xinhaojin** [comment]
> > 如果使用linux，可以执行以下代码，完成部署，未实验生成pdf的功能。
> > ```shell
> > conda create -n got python=3.10 -y
> > conda activate got
> > cd /opt
> > git clone https://github.com/XJF2332/GOT-OCR-2-GUI.git
> > cd GOT-OCR-2-GUI
> > pip install -r requirements-noversion.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
> > mkdir models
> > wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/model.safetensors
> > wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/model.safetensors
> > wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/config.json
> > wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/modeling_GOT.py
> > wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/render_tools.py
> > wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/got_vision_b.py
> > wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/generation_config.json
> > wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/qwen.tiktoken
> > wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/special_tokens_map.json
> > wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/tokenization_qwen.py
> > wget -c https://hf-mirror.com/stepfun-ai/GOT-OCR2_0/resolve/main/tokenizer_config.json
> > cd ..
> > python GUI.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 完成无报错后，可以浏览器访问 http://127.0.0.1:7860/
> 
> 我在执行python GUI.py时 提示RuntimeError: Directory 'static/' does not exist 这个问题要如何解决呢

我也是这个问题

**Comment by KirariSpark** [comment]
这样吧，你们先把这一段注释掉，报错的这一段代码其实根本用不到
![image](https://github.com/user-attachments/assets/567c0819-aed5-4029-8151-d87bcd835bda)

**Comment by KirariSpark** [comment]
简单看了一下，网上说是有什么兼容性问题，先把fitz和pymupdf卸载了，再pip install PyMuPDF就行，不用再pip fitz了
![image](https://github.com/user-attachments/assets/4eaf1de4-f2c4-46b0-975c-0873760cc0dd)

**Comment by sunshinejoesun** [comment]
> 简单看了一下，网上说是有什么兼容性问题，先把fitz和pymupdf卸载了，再pip install PyMuPDF就行，不用再pip fitz了 ![image](https://private-user-images.githubusercontent.com/167102464/376710097-4eaf1de4-f2c4-46b0-975c-0873760cc0dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjA0MTEsIm5iZiI6MTcyOTA2MDExMSwicGF0aCI6Ii8xNjcxMDI0NjQvMzc2NzEwMDk3LTRlYWYxZGU0LWYyYzQtNDZiMC05NzVjLTA4NzM3NjBjYzBkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQwNjI4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2VkZThiZDc4NDczM2IxM2RiYjcyZWIxYjMwNDY0NDBkNDE4Njc0YWQwNjM3ZjJlMDM3Y2M1Y2I1MmMzNjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nTysUCx_hT-tpnCuNmC2Kgy2Hq0BxHiTPsMf3PM3oDE)

按照您的方法，我成功打开了网页，但是在做测试时发现提示NoneType' object has no attribute 'chat'，我尝试修改了GUI中的model和tokenizer中的路径，但并没有解决
![image](https://github.com/user-attachments/assets/cd7fd506-ff02-419b-912c-9050f3b97066)

**Comment by KirariSpark** [comment]
忘了把我测试用的配置文件改回来了😂😂😂你用Config Manager.py把load_model_on_start改成true就行了，路径不用改，这把是我的问题😂😂😂

**Comment by KirariSpark** [comment]
还有什么问题开新issue哈，不要总是在已经关闭的issue下提问了
