### ISSUE TITLE
很多依赖都要重新安装，

### ISSUE THREAD

**Issue by 602387193c** [XJF2332/GOT-OCR-2-GUI#4]
我昨天安装的时候，很多依赖都重新安装了，都用默认的最新版本，作者给的依赖都是有指定版本，其实没必要，反而会造成问题。
我感觉哈，我也不是学计算机的。
我大概想一下，这几个（包括但不限于）依赖好像是直接用pip install 直接重新装的最新版，requirements.txt指定的版本没有安装成功
accelerate
verovio
tiktoken
gradio
transformers

**Comment by KirariSpark** [comment]
安装不成功吗？requirements.txt我是直接从我自己开发用的虚拟环境pip freeze的，不应该会有问题的，我还用pipdeptree看了没有冲突。可能是你后来更新的依赖版本和requirements.txt冲突了

**Comment by 602387193c** [comment]
我是成功安装了项目的，项目安装与依赖问题反馈:
1. 初始安装:
   使用` requirements.txt` 安装了大多数项目指定版本的依赖。
2. 运行时问题:
   在 Win11 系统上运行时,遇到多次模块相关错误(约5-6次)。涉及模块包括 accelerate, verovio, tiktoken, gradio, transformers 等。
3. 问题原因:
 `requirements.txt `中指定的某些版本可能不兼容每个人特定的 Win11 系统。
4. 解决方法:
   对报错的模块,使用 `pip install <模块名>` 安装最新版本,而非使用指定版本。这种方法成功解决了兼容性问题。
5. 过程:
   逐个解决报错,期间使用了 Claude 3.5 AI 对报错信息进行分析和解决。

建议:考虑更新 requirements.txt,为某些依赖提供更灵活的版本选择,以提高兼容性。

**Comment by KirariSpark** [comment]
提供了一个新的requirements-noversion.txt，顺便更新了README，看看

**Comment by 602387193c** [comment]
好的，谢谢啦，希望对-后面的人有用吧。
